import { Car, Settings } from "./types";

export const mockCars: Car[] = [
  {
    id: 1,
    slug: "toyota-avanza-g-2021",
    name: "Toyota Avanza 1.5 G",
    brand: "Toyota",
    price: 185000000,
    year: 2021,
    mileage: 35000,
    transmission: "Manual",
    fuel: "Bensin",
    color: "Silver",
    description: "Kondisi sangat terawat, pemakaian pribadi, pajak hidup.",
    status: "available",
    featured: true,
    images: [{ id: 1, car_id: 1, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    slug: "honda-jazz-rs-2019",
    name: "Honda Jazz 1.5 RS",
    brand: "Honda",
    price: 210000000,
    year: 2019,
    mileage: 42000,
    transmission: "Automatic",
    fuel: "Bensin",
    color: "Kuning",
    description: "Mobil siap pakai, bebas banjir, servis record bengkel resmi.",
    status: "sold",
    featured: true,
    images: [{ id: 2, car_id: 2, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    slug: "mitsubishi-xpander-ultimate-2022",
    name: "Mitsubishi Xpander Ultimate",
    brand: "Mitsubishi",
    price: 250000000,
    year: 2022,
    mileage: 15000,
    transmission: "Automatic",
    fuel: "Bensin",
    color: "Putih",
    description: "Seperti baru, km rendah, garansi dealer masih berlaku.",
    status: "available",
    featured: true,
    images: [{ id: 3, car_id: 3, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    slug: "daihatsu-xenia-r-2020",
    name: "Daihatsu Xenia 1.3 R",
    brand: "Daihatsu",
    price: 160000000,
    year: 2020,
    mileage: 50000,
    transmission: "Automatic",
    fuel: "Bensin",
    color: "Hitam",
    description: "Mesin halus, AC dingin, kaki-kaki empuk.",
    status: "available",
    featured: true,
    images: [{ id: 4, car_id: 4, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    slug: "suzuki-ertiga-gx-2018",
    name: "Suzuki Ertiga 1.5 GX",
    brand: "Suzuki",
    price: 145000000,
    year: 2018,
    mileage: 65000,
    transmission: "Manual",
    fuel: "Bensin",
    color: "Abu-abu",
    description: "Kabin luas, bahan bakar irit, pajak panjang.",
    status: "available",
    featured: false,
    images: [{ id: 5, car_id: 5, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    slug: "toyota-innova-reborn-2017",
    name: "Toyota Innova Reborn 2.4 G",
    brand: "Toyota",
    price: 295000000,
    year: 2017,
    mileage: 80000,
    transmission: "Automatic",
    fuel: "Diesel",
    color: "Hitam",
    description: "Tenaga responsif, interior bersih, dokumen lengkap.",
    status: "available",
    featured: false,
    images: [{ id: 6, car_id: 6, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    slug: "honda-brio-e-2020",
    name: "Honda Brio 1.2 E",
    brand: "Honda",
    price: 135000000,
    year: 2020,
    mileage: 30000,
    transmission: "Automatic",
    fuel: "Bensin",
    color: "Putih",
    description: "City car irit, cocok untuk harian, AC dingin, ban baru.",
    status: "available",
    featured: false,
    images: [{ id: 7, car_id: 7, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    slug: "toyota-rush-trd-2019",
    name: "Toyota Rush 1.5 TRD",
    brand: "Toyota",
    price: 220000000,
    year: 2019,
    mileage: 55000,
    transmission: "Automatic",
    fuel: "Bensin",
    color: "Putih",
    description: "SUV tangguh, fitur lengkap, servis record resmi.",
    status: "available",
    featured: false,
    images: [{ id: 8, car_id: 8, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    slug: "mitsubishi-pajero-dakar-2018",
    name: "Mitsubishi Pajero Dakar",
    brand: "Mitsubishi",
    price: 380000000,
    year: 2018,
    mileage: 70000,
    transmission: "Automatic",
    fuel: "Diesel",
    color: "Hitam",
    description: "Mesin diesel bertenaga, 4x4, interior mewah, siap off-road.",
    status: "available",
    featured: false,
    images: [{ id: 9, car_id: 9, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 10,
    slug: "suzuki-xl7-alpha-2021",
    name: "Suzuki XL7 Alpha",
    brand: "Suzuki",
    price: 195000000,
    year: 2021,
    mileage: 25000,
    transmission: "Manual",
    fuel: "Bensin",
    color: "Abu-abu",
    description: "Crossover stylish, kabin luas 7 penumpang, fitur modern.",
    status: "available",
    featured: false,
    images: [{ id: 10, car_id: 10, image_url: "", sort_order: 1 }],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const mockSettings: Settings = {
  showroom_name: "Garasirumahan",
  phone: "6281234567890",
  address: "Jl. Otomotif No. 123, Jakarta Selatan",
  open_hours: "Senin - Sabtu, 08:00 - 17:00",
  meta_title: "Garasirumahan - Showroom Mobil Bekas Terpercaya",
  meta_description: "Temukan mobil bekas berkualitas dengan harga transparan, dokumen lengkap, dan garansi mesin. Pilihan terbaik di Garasirumahan.",
};

export function getCarBySlug(slug: string): Car | undefined {
  return mockCars.find(car => car.slug === slug);
}

export function getRelatedCars(currentCar: Car, limit = 4): Car[] {
  const sameBrand = mockCars.filter(
    c => c.brand === currentCar.brand && c.id !== currentCar.id
  );
  const others = mockCars.filter(
    c => c.brand !== currentCar.brand && c.id !== currentCar.id
  );
  return [...sameBrand, ...others].slice(0, limit);
}
